services:
  postgres:
    container_name: nvc-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nvc-network

  mailpit:
    container_name: nvc-mailpit
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpitdata:/data
    ports:
      - '8025:8025'
      - '1025:1025'
    env_file:
      - .env
    networks:
      - nvc-network

  adminer:
    container_name: nvc-adminer
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - nvc-network

volumes:
  mailpitdata:
    name: nvc-mailpitdata
  pgdata:
    name: nvc-pgdata

networks:
  nvc-network:
    name: nvc
