services:
  postgres:
    container_name: nvc-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nvc-network

  mailpit:
    container_name: nvc-mailpit
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpitdata:/data
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - nvc-network

volumes:
  mailpitdata:
    name: nvc-mailpitdata
  pgdata:
    name: nvc-pgdata

networks:
  nvc-network:
    name: nvc
